# Generated by Django 3.2.8 on 2021-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211116_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, null=True)),
                ('order_date', models.DateTimeField(null=True)),
                ('order_total', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('is_delivered', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField(null=True)),
                ('Product_quantity', models.IntegerField(null=True)),
                ('Product_Price', models.IntegerField(null=True)),
                ('Subtotal', models.IntegerField(null=True)),
                ('Payment_methos', models.CharField(max_length=40, null=True)),
                ('Paymrnt_status', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
