# Generated by Django 3.2.8 on 2021-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_order_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/user.jpg', upload_to='images/'),
        ),
    ]
