# Generated by Django 3.2.8 on 2021-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
