# Generated by Django 3.2.8 on 2021-11-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('client', '0014_auto_20211120_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
