# Generated by Django 3.2.8 on 2021-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_order_vendor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=40, null=True)),
                ('product_no', models.IntegerField(null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
