# Generated by Django 3.2.8 on 2021-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=40, null=True)),
                ('dplace', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
