# Generated by Django 3.2.8 on 2021-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_delivery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='Image.jpg', upload_to='images/'),
        ),
    ]
